server:
  port: 5000

spring:
  cache:
#    type: simple // time-to-live with simple caching can be used through a scheduler annoted with @CacheEvict
    type: redis
    redis:
      time-to-live: 90S # this is the time after which cache will be auto deleted

  data:
    redis:
      host: localhost
      port: 6379
#      timeout: 1S # this is max time taken to read value from redis
